package org.crudservlet.model;

public enum Permissions {
    HOME_VIEW,
    REQUESTS_VIEW,
    REQUESTS_VIEW_REQUEST,
    REQUESTS_CREATE,
    REQUESTS_CANCEL,
    CLIENTS_VIEW,
    CLIENTS_CREATE,
    CLIENTS_EDIT,
    REPORTS_VIEW,
    REPORT_GENERATE_REQUESTS_DETAILED,
    REPORT_GENERATE_REPORT_REQUESTS_CONSOLIDATED,
    REPORTS_LOAD_REPORT;
}
